services:
  postgres:
    image: postgres:17-alpine # Latest stable, smaller image
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: personal-aditi # Specify default database
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    healthcheck: # Optional: helps other services wait for DB
      test: ['CMD-SHELL', 'pg_isready -U myuser -d personal-aditi']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres: